import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import { authMiddleware, AuthenticatedRequest } from '@/lib/auth'; // Import authMiddleware

const prisma = new PrismaClient();

// GET /api/keys - Fetches all API keys
export const GET = authMiddleware(async (request: AuthenticatedRequest) => {
  try {
    const userId = request.user?.userId;
    const userRole = request.user?.role;

    let whereClause = {};
    if (userRole !== 'ADMIN') {
      whereClause = { userId: userId };
    }

    const apiKeys = await prisma.gatewayApiKey.findMany({
      where: whereClause,
      include: {
        user: true, // Include the related user data
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
    return NextResponse.json(apiKeys, {
      headers: {
        'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0',
      },
    });
  } catch (error) {
    console.error("Error fetching API keys:", error);
    return NextResponse.json({ error: '获取 API 密钥失败' }, { status: 500 });
  }
});

// POST /api/keys - Creates a new API key
export const POST = authMiddleware(async (request: AuthenticatedRequest) => {
  try {
    const userId = request.user?.userId; // Get userId from authenticated request
    if (!userId) {
      return NextResponse.json({ error: '未授权: 用户ID缺失' }, { status: 401 });
    }

    const body = await request.json();
    const { name } = body;

    if (!name) {
      return NextResponse.json({ error: '缺少必填字段: 名称' }, { status: 400 });
    }

    const newApiKey = await prisma.gatewayApiKey.create({
      data: {
        name,
        userId: userId, // Associate the API key with the authenticated user
        // The 'key' field is automatically generated by the database thanks to @default(cuid())
      },
    });

    return NextResponse.json(newApiKey, { status: 201 });
  } catch (error) {
    console.error("Error creating API key:", error);
    return NextResponse.json({ error: '创建 API 密钥失败' }, { status: 500 });
  }
});
