"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-21 03:16:59.365693

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "input_price_per_million",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
        ),
        sa.Column(
            "output_price_per_million",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
        ),
        sa.Column(
            "routing_strategy",
            sa.Enum("weighted_random", name="routing_strategy"),
            server_default="weighted_random",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("credential_encrypted", mysql.LONGBLOB(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("auto_load_models", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "model_sync_interval_seconds",
            sa.Integer(),
            server_default=sa.text("3600"),
            nullable=False,
        ),
        sa.Column("last_model_sync_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "user", name="user_role"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("totp_secret_encrypted", sa.LargeBinary(length=512), nullable=True),
        sa.Column("totp_enabled", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "balance",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
        ),
        sa.Column(
            "total_spent",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column("key_hash", sa.BINARY(length=32), nullable=False),
        sa.Column(
            "scope",
            sa.Enum("all", "providers", "models", "providers_and_models", name="api_key_scope"),
            server_default="all",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_table(
        "model_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
    )
    op.create_table(
        "provider_protocols",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column(
            "protocol", sa.Enum("openai", "claude", "gemini", name="protocol"), nullable=False
        ),
        sa.Column("base_url", sa.String(length=512), nullable=False),
        sa.Column("websocket_url", sa.String(length=2048), nullable=True),
        sa.Column("extra_headers_encrypted", mysql.LONGBLOB(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider_id",
            "protocol",
            "base_url",
            name="uq_provider_protocols_provider_protocol_base_url",
        ),
    )
    op.create_table(
        "api_key_models",
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.PrimaryKeyConstraint("api_key_id", "model_id"),
    )
    op.create_table(
        "api_key_providers",
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("api_key_id", "provider_id"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.CHAR(length=36), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "reservation", "reservation_release", "usage", "adjustment", name="ledger_kind"
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "model_routes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("provider_protocol_id", sa.Integer(), nullable=False),
        sa.Column("upstream_model", sa.String(length=255), nullable=False),
        sa.Column("weight", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "runtime_state",
            sa.Enum("closed", "open", "half_open", name="route_runtime_state"),
            server_default="closed",
            nullable=False,
        ),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("disabled_until", sa.DateTime(), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_protocol_id"],
            ["provider_protocols.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "model_id",
            "provider_id",
            "provider_protocol_id",
            name="uq_model_routes_model_provider_protocol",
        ),
    )
    op.create_index(
        "ix_model_routes_model_enabled_runtime_state",
        "model_routes",
        ["model_id", "enabled", "runtime_state"],
        unique=False,
    )
    op.create_table(
        "request_logs",
        sa.Column("id", sa.CHAR(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=True),
        sa.Column("model_route_id", sa.Integer(), nullable=True),
        sa.Column(
            "inbound_protocol",
            sa.Enum("openai", "claude", "gemini", name="protocol"),
            nullable=False,
        ),
        sa.Column(
            "outbound_protocol",
            sa.Enum("openai", "claude", "gemini", name="protocol"),
            nullable=True,
        ),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column("stream", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("started", "completed", "failed", "client_disconnected", name="request_status"),
            server_default="started",
            nullable=False,
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "usage_source", sa.Enum("provider", "estimated", name="usage_source"), nullable=True
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("first_token_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("request_detail_gzip", mysql.LONGBLOB(), nullable=True),
        sa.Column("response_detail_gzip", mysql.LONGBLOB(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_route_id"],
            ["model_routes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_request_logs_api_key_created_at",
        "request_logs",
        ["api_key_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_request_logs_provider_created_at",
        "request_logs",
        ["provider_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_request_logs_status_created_at", "request_logs", ["status", "created_at"], unique=False
    )
    op.create_index(
        "ix_request_logs_user_created_at", "request_logs", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_logs")
    op.drop_table("model_routes")
    op.drop_table("ledger_entries")
    op.drop_table("api_key_providers")
    op.drop_table("api_key_models")
    op.drop_table("provider_protocols")
    op.drop_table("model_aliases")
    op.drop_table("api_keys")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("providers")
    op.drop_table("models")
    # ### end Alembic commands ###
